### ISSUE TITLE
Epic: Performance Optimizations

### ISSUE THREAD

**Issue by brentleyjones** [MobileNativeFoundation/rules_xcodeproj#2044]
This issue will track know areas that we can improve the performance: Bazel memory usage, analysis phase wall-time, and `generator` wall-time.

## Bazel memory

- [x] #2045
- [x] #2049
- [x] #2052
- [x] #2053
- [x] #2056
- [x] #2059
- [x] #2067
- [x] #2073
- [x] #2074
- [x] #2076
- [x] #2079
- [x] #2081
- [x] #2086
- [x] #2087
- [x] #2090
- [x] #2094
- [x] #2095
- [x] #2096
- [x] #2098
- [x] #2099
- [x] #2101
- [x] #2102
- [x] #2104
- [x] #2105
- [x] #2107
- [x] #2110
- [x] #2212
- [x] Reduce size of `xcode_target`

## Analysis phase time

- [x] #2063
- [x] #2082
- [x] #2083
- [x] #2089
- [x] #2112
- [x] #2114
- [x] #2115
- [x] #2116
- [x] #2119
- [x] #2129
- [x] #2130
- [x] #2134
- [x] #2212
- [x] Normalizing file paths could happen as part of `args()`? Maybe move spec creation into its own action (similar to `swift_debug_settings.py`.

## `generator` time

- [x] #2043 
- [x] #2042 
- [x] `XcodeProj.write()` is largely serial

**Comment by jpsim** [comment]
I'm taking a look at parallelizing `XcodeProj.write()`.
