### ISSUE TITLE
Epic: Target Merging 

### ISSUE THREAD

**Issue by thiagohmcruz** [MobileNativeFoundation/rules_xcodeproj#2301]
Tracks "Target Merging" related issues. Resolving this epic should deliver:

* Better integration with other rule sets (e.g. `rules_ios`)
* Improved IDE responsiveness in big codebases

### Tasks

- [ ] https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/1724
- [ ] https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/1929
- [ ] https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/1351
- [ ] https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/2021
